repos:
  - repo: https://github.com/snakemake/snakefmt
    rev: v0.6.0
    hooks:
      - id: snakefmt
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
  - repo: https://github.com/lorenzwalthert/precommit
    rev: v0.2.2.9015
    hooks:
      - id: style-files
        args: [--style_pkg=styler, --style_fun=tidyverse_style, --cache-root=styler-perm]
