dataset: otu_large
outcome_colname: dx
method:
 - glmnet
 - rf
kfold: 5
ncores: 4
nseeds: 100
find_feature_importance: false
exclude_param_keys:
 - exclude_param_keys
 - outcome_colname
 - ncores
 - nseeds
 - find_feature_importance
 - hyperparams
 - paramspace_csv
