dataset: otu_large
outcome_colname: dx
method:
 - glmnet
 - rf
kfold: 5
ncores: 8
nseeds: 10
find_feature_importance: true
hyperparams:
paramspace_csv: 'config/custom-paramspace.csv'
exclude_param_keys:
 - exclude_param_keys
 - outcome_colname
 - ncores
 - nseeds
 - find_feature_importance
 - hyperparams
 - paramspace_csv
