dataset_csv: data/processed/otu-large.csv
dataset_name: otu-large
outcome_colname: dx
ml_methods:
 - glmnet
 - rf
 - svmRadial
kfold: 5
ncores: 8
nseeds: 10
find_feature_importance: false
hyperparams:
  - parRF:
    - mtry:
      - 42
      - 83
      - 166

