dataset_csv: data/processed/otu-large.csv
dataset_name: otu-large
outcome_colname: dx
ml_methods:
 - glmnet
 - parRF
 - svmRadial
kfold: 5
ncores: 8
nseeds: 10
hyperparams:
  - parRF:
    - mtry:
      - 42
      - 83
      - 166