name: smk-ML
channels:
  - conda-forge
  - bioconda
  - defaults
  - r
dependencies:
  - python=3
  - r-base=4
  - r-caret
  - r-devtools
  - r-doFuture
  - r-dplyr
  - r-foreach
  - r-future
  - r-future.apply
  - r-ggplot2
  - r-here
  - r-kernlab
  - r-liblinear
  - r-prroc
  - r-randomForest
  - r-rcolorbrewer
  - r-readr
  - r-rlang
  - r-rmarkdown
  - r-rpart
  - r-xgboost
  - snakemake=5
