dataset_csv: data/processed/otu-large.csv
dataset_name: otu-large
outcome_colname: dx
methods:
 - glmnet
 - rf
kfold: 5
ncores: 16
nseeds: 50
find_feature_importance: false
exclude_param_keys:
 - exclude_param_keys
 - outcome_colname
 - ncores
 - nseeds
 - find_feature_importance
 - hyperparams
