dataset-csv: data/processed/otu-large.csv
dataset-name: otu-large
outcome-colname: dx
ml-methods:
 - glmnet
 - rf
 - rpart2
 - svmRadial
kfold: 5
ncores: 36
nseeds: 100
find-feature-importance: false
hyperparams:
  - glmnet:
    - alpha: 
      - 0
    - lambda:
      - 0.0001
      - 0.001
      - 0.01
      - 0.1
      - 1
      - 10
  - rf:
    - mtry:
      - 42
      - 83
      - 166

