dataset: otu_large
outcome_colname: dx
ml_method:
 - glmnet
 - rf
 - rpart2
 - svmRadial
kfold: 5
ncores: 36
nseeds: 100
find_feature_importance: false
hyperparams:
  - glmnet:
    - alpha: 
      - 0
    - lambda:
      - 0.0001
      - 0.001
      - 0.01
      - 0.1
      - 1
      - 10
  - rf:
    - mtry:
      - 42
      - 83
      - 166
exclude_param_keys:
 - exclude_param_keys
 - outcome_colname
 - ncores
 - nseeds
 - find_feature_importance
 - hyperparams
