dataset-csv: data/processed/otu-mini-bin.csv
dataset-name: otu-mini-bin
outcome-colname: dx
ml-methods:
 - glmnet
kfold: 2
ncores: 4
nseeds: 2
find-feature-importance: true
hyperparams:
  - glmnet:
    - alpha: 
      - 0
    - lambda:
      - 0.0001
      - 0.001
      - 0.01
      - 0.1
      - 1
      - 10
