dataset: otu_micro
outcome_colname: dx
ml_method:
 - glmnet
kfold: 2
ncores: 4
nseeds: 2
find_feature_importance: true
hyperparams:
  - glmnet:
    - alpha: 
      - 0
    - lambda:
      - 0.0001
      - 0.001
      - 0.01
      - 0.1
      - 1
      - 10
exclude_param_keys:
 - exclude_param_keys
 - outcome_colname
 - ncores
 - nseeds
 - find_feature_importance
 - hyperparams
