name: run-snakemake

on: 
  workflow_dispatch:
    inputs:
      configfile:
        description: "Path to the config file"
        required: true
        default: 'config/test.yaml'
        type: string

jobs:
  run-snakemake:
    runs-on: ubuntu-latest-16-cores
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Print config file
        run: |
          echo "Using config file: ${{ inputs.configfile }}"
          cat ${{ inputs.configfile }}
      - name: Run the snakemake workflow
        uses: snakemake/snakemake-github-action@v1.24.0
        with:
          directory: .
          snakefile: workflow/Snakefile
          args: "archive --cores 16 --use-conda --conda-frontend mamba --show-failed-logs --configfile ${{ inputs.configfile }}"
      - name: Upload logs on failure
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: log
          path: log/
      - name: Upload archive on success
        uses: actions/upload-artifact@v3
        with:
          name: workflow-results
          path: workflow_*.zip
          if-no-files-found: warn
  
