name: tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: workflow/envs/github-actions.yml
          cache-environment: true
      - name: Lint workflow
        uses: snakemake/snakemake-github-action@v1.24.0
        with:
          directory: .
          snakefile: workflow/Snakefile
          args: "--lint"
      - name: Test with pytest
        shell: bash -el {0}
        run: |
          pytest tests/
